source "https://rubygems.org"

# Web framework
gem "rack_csrf"
gem "roda", "~> 2.15"
gem "tilt"

# Database
gem "sequel"
gem "sqlite3"

# Attachments
gem "aws-sdk", "~> 2.1"
gem "dotenv"
gem "shrine", path: ".."

# Processing
gem "image_processing"
gem "mini_magick"

# Background jobs
gem "sucker_punch", "~> 2.0"

# Debugging
gem "pry-byebug"
